---
- name: Check if there is "{{ ansible_user_dir }}/.bash_aliases"
  stat:
    path: "{{ ansible_user_dir }}/.bash_aliases"
  become: false
  register: result

- name: Create "{{ ansible_user_dir }}/.bash_aliases"
  file:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    state: touch
  when: not result.stat.exists

- name: Add alias in "{{ ansible_user_dir }}/.bash_aliases"
  blockinfile:
    path: "{{ ansible_user_dir }}/.bash_aliases"
    block: |
      alias vi="vim"
      alias ap="ansible-playbook"

- name: Download vim-atom-dark
  git:
    repo: "https://github.com/gosukiwi/vim-atom-dark.git"
    dest: "{{ playbook_dir}}/roles/os/files/vim-atom-dark"

- name: Create directory for color scheme
  file:
    path: "{{ ansible_user_dir }}/.vim/colors"
    state: directory

- name: Copy color scheme
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.vim/colors/"
  with_fileglob:
    - "vim-atom-dark/colors/*.vim"

- name: Copy "{{ ansible_user_dir }}/.vimrc"
  copy:
    src: .vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"

- name: Download git-completion and git-prompt
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_user_dir }}/{{ item.file }}"
    mode: "0755"
  with_items:
    - {
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash",
        file: ".git-completion.bash"
      }
    - {
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh",
        file: ".git-prompt.sh"
      }

- name: Load git-completion
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: 'source \$HOME/.git-completion.bash'
    line: "source $HOME/.git-completion.bash"

- name: Load git-prompt
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: 'source \$HOME/.git-prompt.sh'
    line: "source $HOME/.git-prompt.sh"

- name: Config git-prompt
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      GIT_PS1_SHOWDIRTYSTATE=1
      GIT_PS1_SHOWUPSTREAM=1
      GIT_PS1_SHOWUNTRACKEDFILES=
      GIT_PS1_SHOWSTASHSTATE=1
      export PS1='\[\033[1;32m\]\u\[\033[00m\]:\[\033[1;34m\]\w\[\033[1;31m\]$(__git_ps1)\[\033[00m\] \$ '
