---
- name: Download git-completion and git-prompt
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_user_dir }}/{{ item.file }}"
    mode: "0755"
  with_items:
    - {
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash",
        file: ".git-completion.bash"
      }
    - {
        url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh",
        file: ".git-prompt.sh"
      }

- name: Add git-completion loading 
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "source $HOME/.git-completion.bash"

- name: Load git-prompt
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "source $HOME/.git-prompt.sh"

- name: Config git-prompt
  blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      GIT_PS1_SHOWDIRTYSTATE=1
      GIT_PS1_SHOWUPSTREAM=1
      GIT_PS1_SHOWUNTRACKEDFILES=1
      GIT_PS1_SHOWSTASHSTATE=1
      export PS1='\[\033[1;32m\]\u\[\033[00m\]:\[\033[1;34m\]\w\[\033[1;31m\]$(__git_ps1)\[\033[00m\] \$ '
