---
- name: install epel and remi package
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest

- name: install GPG keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
      - https://rpms.remirepo.net/RPM-GPG-KEY-remi
      - https://rpms.remirepo.net/RPM-GPG-KEY-remi2017
      - https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
      - https://rpms.remirepo.net/RPM-GPG-KEY-remi2019

- name: install php
  yum:
    name: php
    state: latest
    enablerepo: remi,remi-php73
