---
- name: Install remi repository
  dnf:
    name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present

- name: Install php{{ php_version }}
  dnf:
    name: "php{{ php_version }}"
    state: present

- name: Change execution name php80 to php
  alternatives:
    name: php
    path: /usr/bin/php80
    link: /usr/bin/php
