---
- name: Install vim
  become: yes
  yum:
    name: "vim"
    state: present

- name: Add alias for vim to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "alias vi='vim'"

- name: Download vim-atom-dark
  git:
    repo: "https://github.com/gosukiwi/vim-atom-dark.git"
    dest: "/usr/local/src/vim-atom-dark"

- name: Create directory for color scheme
  file:
    path: "{{ ansible_user_dir }}/.vim/colors"
    state: directory

- name: Copy color scheme
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.vim/colors/"
    remote_src: yes
  with_fileglob:
    - "/usr/local/src/vim-atom-dark/colors/*.vim"

- name: Copy "{{ ansible_user_dir }}/.vimrc"
  copy:
    src: .vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
